[package]
name = "wasi-mobilenet-inference"
version = "0.1.0"
authors = ["Radu M <root@radu.sh>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
tract = "0.11.0"
tract-tensorflow = "0.11.0"
image = { version = "0.23.0", default-features = false, features = ["jpeg"] }
